device: cuda:0
encoder_type: esm2_t33_650M
sub_parent_dir: src

data:
  train_labels: data/active_site/Enzyme_active_sites_train.txt
  test_labels: data/active_site/Enzyme_active_sites_test.txt

scripts:
  generate_embedding: tasks/downstream/active_site/scripts/generate_per_residue_embeddings.py
  train_kfold: tasks/downstream/active_site/src/train_kfold.py
  knn_active_site: tasks/downstream/active_site/src/knn_active_site.py

emb_root: embeddings/as/06B

models:
  esm2_t33_650M_base:
    mode: base
  esm2_t33_650M_cpt:
    mode: cpt
  esm2_t33_650M_base_sub:
    mode: base_sub
  esm2_t33_650M_cpt_sub:
    mode: cpt_sub

eval:
  methods: [mlp]
  seeds: [2025, 2026, 3047]
  mlp:
    model_type: mlp
    loss_type: focal
    focal_alpha: 0.65
    focal_gamma: 2.0
    lr: 1.0e-3
    weight_decay: 1.0e-4
    batch_size: 16
    dropout: 0.1
    epochs: 35
    patience: 4
    n_splits: 5
  knn:
    ks: [1]

results_root: artifacts/downstream/active_site/results/enzsub06B
