common:
  ec_level: 4
  match_mode: any_overlap

hcft_eval:
  embedding_dirs:
    esm2_base: artifacts/downstream/ec/embeddings/esm2_t33_650M/paper/esm2_t33_650M_base
    esm2_cpt: artifacts/downstream/ec/embeddings/esm2_t33_650M/paper/esm2_t33_650M_cpt
    esm2_base_sub: artifacts/downstream/ec/embeddings/esm2_t33_650M/paper/base_sub_r16_ecfp
    esm2_cpt_sub: artifacts/downstream/ec/embeddings/esm2_t33_650M/paper/cpt_sub_r16_ecfp

  label_csv: data/ec/split100.csv
  identity_pairs: artifacts/downstream/ec/hcft/identity_pairs/split100/pair_identity.csv
  output_dir: artifacts/downstream/ec/hcft/experiments/06B_strict_triplets

  negative_mode: general

  positive_max_identity: 30.0
  negative_min_identity: 40.0
  min_identity_margin: 10.0

  n_neg_per_pos: 5
  max_pos_per_anchor: 200
  max_neg_per_anchor: 500
  max_triplets_per_anchor: 1000
  min_triplets_per_anchor: 10
  n_seeds: 1
  baseline_name: esm2_base
  chunk_size: 100000
  save_triplets: true